//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcertCI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConcertNotifierEntities1 : DbContext
    {
        public ConcertNotifierEntities1()
            : base("name=ConcertNotifierEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblConcerts> tblConcerts { get; set; }
        public virtual DbSet<tblGroups> tblGroups { get; set; }
        public virtual DbSet<tblSubscriptions> tblSubscriptions { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblNotifications> tblNotifications { get; set; }
    }
}
