//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcertCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotifications
    {
        public int concert_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime notification_date { get; set; }
    
        public virtual tblConcerts tblConcerts { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
